// Code generated by logcopter-gen; DO NOT EDIT.

package asyncprovider

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.bobatea.pkg.tui.asyncprovider")
