// Code generated by logcopter-gen; DO NOT EDIT.

package textarea

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.bobatea.pkg.textarea")
